name: Continuous translation integration
on:
  schedule:
    # Once per hour
    - cron: '* * * * *'
jobs:
  sync_translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push recent translations to latest-translation branch
        env:
          IMPORT_LANG: cs
        run: |
          echo $(date +%F) >> latest_test_timestamp
          _scripts/git-push.sh latest-translation/$IMPORT_LANG "Update test_timestamp"
