name: Preview translations

on:
  repository_dispatch:

jobs:
  pull_push_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/cache/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Pull Lokalize translations
        env:
          LOCALIZE_TOKEN: ${{ secrets.LOCALIZE_TOKEN }}
          IMPORT_LANG: ${{ github.event.client_payload.lang }}
        run: |
          mv docker-compose.ci.yml docker-compose.override.yml
          ./import-translations.sh $LOCALIZE_TOKEN $IMPORT_LANG
          mv docker-compose.override.yml docker-compose.ci.yml
      - name: Commit changes to Branch
        env:
          IMPORT_LANG: ${{ github.event.client_payload.lang }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: preview-translation-workflow
        run: _scripts/git-push.sh preview/latest/$IMPORT_LANG "sync $IMPORT_LANG"
      - name: Build Jekyll site
        run: |
          mv docker-compose.ci.yml docker-compose.override.yml
          docker-compose run --rm web /bin/bash -c "(bundle check || bundle install --jobs=3) && bundle exec jekyll build"
      - name: Deploy to translation-preview repo
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_NAME: rousik/guide-translation-preview-${{ github.event.client_payload.lang }}
          BRANCH: gh-pages
          FOLDER: build

